### ISSUE TITLE
PST box should support light and voice keys

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1309]
Currently we're limited to the 5 hardware buttons.

http://discourse.psychopy.org/t/pst-serial-response-box-refresh-detector/1508/4?u=richard

**Comment by martharobinson** [comment]
Addressed in #1553 - although the suggestion in the linked thread to add "light_on" and "light_off" events was not implemented and might also be worthwhile.

**Comment by hoechenberger** [comment]
I'll leave this open for now – new events would, imho, definitely be the better option.

**Comment by peircej** [comment]
Do PST boxes still exist to support or shall we close this one down?

**Comment by hoechenberger** [comment]
I would consider them legacy and advice users to switch to something else these days.
