### ISSUE TITLE
python3 and iohub.fix_encoding

### ISSUE THREAD

**Issue by tjwilli58** [psychopy/psychopy#1759]
Trying out 1.90-dev3, using Python 3.6 under Anaconda, I get an error when trying to import iohub:

`TypeError: startswith first arg must be bytes or a tuple of bytes, not str`

I think fix_win_sys_argv(encoding) only needs to be called in Python2 right? How about changing fix_encoding to add a check for the python version: 

```
def fix_encoding():
    """Fixes various encoding problems on all platforms.

    Should be called at the very begining of the process.

    """
    ret = True
    if sys.platform == 'win32':
        ret &= fix_win_codec()

    ret &= fix_default_encoding()

    if sys.platform == 'win32' and sys.version_info[0]<3:
        encoding = sys.getdefaultencoding()
        ret &= fix_win_sys_argv(encoding)
        ret &= fix_win_console(encoding)
    return ret

```

**Comment by peircej** [comment]
Sounds good. I'm afraid the python3 compatibility is likely to have quite a few issues, especially around iohub at the moment. But it's great to see you finding solutions. My guess is that you're right about the encoding issues only being needed on Py2, or at least they'll be *different* issues on Py3!

Do you want to submit a pull request with this fix? By the way, I'm afraid this won't make it into the 1.90.0 release at this point but if your commit message says BF: at the beginning then it will be in 1.90.1 (which will hopefully be a fairly quick extra release)

**Comment by tjwilli58** [comment]
I haven't done pull requests before. Let me read up on it a little first. That may prompt me to think a little more about Py2 vs Py3 encoding before I submit a pull request.

**Comment by tjwilli58** [comment]
Not comfortable with doing a pull request just yet. I'll post the requested change in the Development forum.

**Comment by peircej** [comment]
Well, it's OK. I can implement it myself from what you've said - it's just that if I do it myself you won't be credited in the project history as having solved this problem. But I don't mind if you don't feel confident yet

**Comment by tjwilli58** [comment]
I modified the above fix slightly in the 

https://discourse.psychopy.org/t/python3-and-iohub-fix-encoding/4056/3

**Comment by dvbridges** [comment]
@peircej have we included this fix? If not, I could put the above in the next iohub pull request - all credit to @tjwilli58 .

**Comment by hoechenberger** [comment]
I can successfully import `iohub` on Python 3, so I guess this issue is resolved.

**Comment by tjwilli58** [comment]
I just upgraded to 1.90.2, and can also import iohub, but the launchHub.py test still fails. 

Running from inside PsychopyApp:


```
Welcome to PsychoPy2!
v1.90.2

##### Running: C:\Users\timothy.j.williams1\demos.py3\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:

 ** PRESS A KEY TO CONTINUE.....
A Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 187.5, 'unit_type': b'mm'}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
Traceback (most recent call last):
  File "C:\Users\timothy.j.williams1\demos.py3\coder\iohub\launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "C:\Users\timothy.j.williams1\demos.py3\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1

##### Running: C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:

 ** PRESS A KEY TO CONTINUE.....
A Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 187.5, 'unit_type': b'mm'}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
ioHub Server Process Completed With Code:  1
Traceback (most recent call last):
  File "C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server

```

**Comment by tjwilli58** [comment]
What is 
`        exp_code = 'gap_endo_que'
`
in launchHub.testUsingPsychoPyMonitorConfig() and launchHub.testEnabledDataStore() ?

**Comment by tjwilli58** [comment]
Last 2 posts by me should have been in thread #1811

**Comment by rosskempner** [comment]
Hi @tjwilli58 @peircej , I am now getting the same issue on all of the recent psychopy releases. I have been using standalone macos downloads. Do you have any suggestions for fixes?
```

  File "/Applications/PsychoPy 4.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/__init__.py", line 944, in _startServer
    self._osxKillAndFreePort()
  File "/Applications/PsychoPy 4.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/__init__.py", line 1348, in _osxKillAndFreePort
    if line.startswith('Python'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by tjwilli58** [comment]
@rosskempner ,
I’m doing other things now, and it’s been years since I’ve used psychopy. I can’t help. Sorry
