### ISSUE TITLE
Warning: msgpack_numpy could not be imported. 

### ISSUE THREAD

**Issue by jdkoen** [psychopy/psychopy#2298]
I get the following error running my study from the Builder:

Warning: msgpack_numpy could not be imported. This may cause issues for iohub. I'm running 3.0.5 on a Windows 10 machine. 

I looked in the PsychoPy3 installation directory (Lib/site-packages) and find no files for the missing library. This is present in PsychoPy2 (1.90.3) which is also installed on my machine.

**Comment by dvbridges** [comment]
Thanks @jdkoen . I think this has been resolved earlier this year, see https://github.com/psychopy/psychopy/pull/2201

**Comment by hoechenberger** [comment]
@dvbridges But `msgpack-numpy` is apparently still missing from the standalone package – @jdkoen used the latest release! :)

**Comment by dvbridges** [comment]
Sure I saw that, just wanted to post the link to your pull req :)

**Comment by jdkoen** [comment]
It looks like this is specific to the 32-bit install (which I installed by mistake). The 64-bit install seems to have msgpack_numpy installed. 

One solution I found was to just download [msgpack_numpy](https://github.com/lebedov/msgpack-numpy/releases/tag/0.4.4), extract the files, and copy the msgpack_numpy to the C:\Program Files\PsychoPy3\Lib\site-packages\ directory.

**Comment by peircej** [comment]
I'm pretty sure this is has been fixed for some time
