### ISSUE TITLE
[Python 3.9 incompatibility] unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by papr** [psychopy/psychopy#4142]
I am aware that https://www.psychopy.org/download.html#developers-install recommends using Python 3.6. [But with its end-of-life approaching in December](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule), I wanted to raise awareness about incompatibilities with the latest Python release, version 3.9.

One of the incompatibilities is that PsychoPy uses the `encoding` keyword argument when calling `json.loads` (e.g. [here](https://github.com/psychopy/psychopy/blob/2021.2.0/psychopy/monitors/calibTools.py#L456)). [The keyword argument has been removed in Python 3.9](https://docs.python.org/3/library/json.html#json.loads).

Example traceback cause by this issue:
```py
Traceback (most recent call last):
  File ".../psychopy/psychopy/iohub/server.py", line 662, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File ".../psychopy/psychopy/iohub/server.py", line 829, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File ".../psychopy/psychopy/iohub/devices/display/__init__.py", line 58, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File ".../psychopy/psychopy/iohub/devices/display/__init__.py", line 502, in _addRuntimeInfoToDisplayConfig
    self._createPsychopyCalibrationFile()
  File ".../psychopy/psychopy/iohub/devices/display/__init__.py", line 694, in _createPsychopyCalibrationFile
    psychoMonitor = monitors.Monitor(
  File ".../psychopy/psychopy/monitors/calibTools.py", line 126, in __init__
    self._loadAll()
  File ".../psychopy/psychopy/monitors/calibTools.py", line 445, in _loadAll
    self.calibs = json_tricks.load(thisFile, ignore_comments=False,
  File ".../psychopy/env/lib/python3.9/site-packages/json_tricks/nonp.py", line 266, in load
    return loads(string, preserve_order=preserve_order, ignore_comments=ignore_comments, decompression=decompression,
  File ".../psychopy/env/lib/python3.9/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by peircej** [comment]
It looks like this was fixed back in January with #3470 and that has certainly been applied to both our dev and release trunks
@papr is your copy of the repo up to date?

**Comment by papr** [comment]
Probably my bad then. I can't check right now. I will close the issue and reopen it in case I can confirm that the issue persists.
