### ISSUE TITLE
Slider and button not picking up software-triggered mouse click event

### ISSUE THREAD

**Issue by derekwacks** [psychopy/psychopy#4751]
Hello,

We are using pynput (also tried with pyautogui) to input mouse clicks and keyboard presses (instead of physical mouse clicks and keyboard presses). The psychopy experiment responds to the software-triggered keyboard presses, however it does not respond to the software-triggered mouse input. The experiment is responsive to physical keyboard/mouse-triggered events, and the software-triggered events work outside of the psychopy experiment window (on the desktop or in other apps). 

Have you run into this before? 
Where is the code relevant to input events so I may dig into why this might be happening? (I believe the psychopy mouse event code is built on pygame, though I am not entirely sure). 

Thank you!

macOS Big Sur 11.2.3 and Windows 10
Psychopy v2021.2.3
Python 3.8

**Comment by mdcutone** [comment]
Created a PR patch that should fix this issue.

**Comment by derekwacks** [comment]
Hello, 

This problem still persists with the new Psychopy release referenced here #4755 

A related issue might be this warning I get starting psychopy:
`WARNING: pytables package not found. ioHub functionality will be disabled.`

However, I have tried by installing tables explicitly through pip and pytables through conda in the conda env I am using, and the warning still occurs. It seems unlikely ioHub is fully disabled if psychopy is still picking up keyboard input?
