### ISSUE TITLE
[Bug]: Extremely slow rendering of colors

### ISSUE THREAD

**Issue by fredcallaway** [psychopy/psychopy#6353]
### PsychoPy Version

2024.1.0

### What OS are your PsychoPy running on?

macOS Intel

### Bug Description

My task is an interactive game with about 100 elements on the screen (see image below). I'm using a gaze contingent display, so I call flip on every frame. I'm getting about 12 frames per second on average, which makes animations look terrible, produces noticeable lag between input and response, and leads to frequent missed click events.

I did some profiling and almost all the run time is spent in `Color.__deepcopy__`. Maybe I'm naive, but it seems like rendering a red circle shouldn't take so much CPU time.

Is there anything to be done here? Or should I assume that psychopy isn't meant to handle complex graphics and switch to pure pygame?

I appreciate any help anyone can provide here!

<img width="779" alt="image" src="https://github.com/psychopy/psychopy/assets/7883156/365ad9d5-1c62-4128-9a6d-ee9381c0d076">

### Expected Behaviour

Frame rates of at least 30Hz, ideally 60.

### Steps to Reproduce

I can try to produce a minimal example if there's actually interest in working on this.

**Comment by fredcallaway** [comment]
Here's a quick fix that's working for me. In `Color.render` I check if `self.contrast` is 1 and bypass the copy step if so.

```python
# Transform contrast to match rgb
contrast = self.contrast
if contrast == 1:
    return getattr(self, space)
    
contrast = np.reshape(contrast, (-1, 1))
contrast = np.hstack((contrast, contrast, contrast))
...
```

**Comment by TEParsons** [comment]
@cmacmillan noticed the same thing and I've spoken to them previously about solutions, there's some discussion in this PR: https://github.com/psychopy/psychopy/pull/5790

**Comment by TEParsons** [comment]
Fixed by #6720 (I think)

**Comment by aforren1** [comment]
I don't think it's fixed for all cases, e.g. profiling

```
from psychopy import visual
from timeit import default_timer
from statistics import mean, median

w = visual.Window([400, 400], checkTiming=False)
txt = visual.TextBox2(w, text='Text', units='norm', size=(2,2), alignment='center', letterHeight=0.1)

times = []
for i in range(100):
    t0 = default_timer()
    txt.draw()
    times.append(default_timer() - t0)
    w.flip()

w.close()

print(f'median: {median(times)}, mean: {mean(times)}') # ~3ms with profiling turned off
```
suggests that each modification/validation of a color takes on the order of ~500us, and some stimuli assume that it's free?

<details>

<summary>Full profiling output</summary>

```
Timer unit: 1e-06 s

Total time: 0.334814 s
File: C:\Users\adf44\Documents\python\psychopy\psychopy\visual\textbox2\textbox2.py
Function: palette at line 317

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   317                                               @property
   318                                               @line_profiler.profile
   319                                               def palette(self):
   320                                                   """Describes the current visual properties of the TextBox in a dict"""
   321       300        620.1      2.1      0.2          self._palette = {
   322       300        263.9      0.9      0.1              False: {
   323       300        264.9      0.9      0.1                  'lineColor': self._borderColor,
   324       300        203.2      0.7      0.1                  'lineWidth': self.borderWidth,
   325       300        305.0      1.0      0.1                  'fillColor': self._fillColor
   326                                                       },
   327       300        187.9      0.6      0.1              True: {
   328       300     181136.0    603.8     54.1                  'lineColor': self._borderColor-0.1,
   329       300        275.3      0.9      0.1                  'lineWidth': self.borderWidth+1,
   330       300     149786.5    499.3     44.7                  'fillColor': self._fillColor+0.1
   331                                                       }
   332                                                   }
   333       300       1770.9      5.9      0.5          return self._palette[self.hasFocus]

Total time: 0.419377 s
File: C:\Users\adf44\Documents\python\psychopy\psychopy\visual\textbox2\textbox2.py
Function: draw at line 1214

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
  1214                                               @line_profiler.profile
  1215                                               def draw(self):
  1216                                                   """Draw the text to the back buffer"""
  1217                                                   # Border width
  1218       100     142612.3   1426.1     34.0          self.box.setLineWidth(self.palette['lineWidth']) # Use 1 as base if border width is none
  1219                                                   #self.borderWidth = self.box.lineWidth
  1220                                                   # Border colour
  1221       100     118136.5   1181.4     28.2          self.box.setLineColor(self.palette['lineColor'], colorSpace='rgb')
  1222                                                   #self.borderColor = self.box.lineColor
  1223                                                   # Background
  1224       100     107920.0   1079.2     25.7          self.box.setFillColor(self.palette['fillColor'], colorSpace='rgb')
  1225                                                   #self.fillColor = self.box.fillColor
  1226
  1227                                                   # Inherit win
  1228       100        594.1      5.9      0.1          self.box.win = self.win
  1229       100        367.1      3.7      0.1          self.contentBox.win = self.win
  1230       100        331.2      3.3      0.1          self.boundingBox.win = self.win
  1231
  1232       100         52.5      0.5      0.0          if self._needVertexUpdate:
  1233                                                       #print("Updating vertices...")
  1234         1        509.6    509.6      0.1              self._updateVertices()
  1235       100        449.4      4.5      0.1          if self.fillColor is not None or self.borderColor is not None:
  1236       100      18683.6    186.8      4.5              self.box.draw()
  1237
  1238                                                   # Draw sub-elements if in debug mode
  1239       100         79.0      0.8      0.0          if debug:
  1240                                                       self.contentBox.draw()
  1241                                                       self.boundingBox.draw()
  1242
  1243       100        356.8      3.6      0.1          tightH = self.boundingBox._size.pix[1]
  1244       100        200.5      2.0      0.0          areaH = self.contentBox._size.pix[1]
  1245       100        101.9      1.0      0.0          if self.overflow in ("scroll",) and tightH > areaH:
  1246                                                       # Draw scrollbar
  1247                                                       self.scrollbar.draw()
  1248                                                       # Scroll
  1249                                                       if self._alignY == "top":
  1250                                                           # Top aligned means scroll between 1 and 0, and no adjust for line height
  1251                                                           adjMulti = (-self.scrollbar.markerPos + 1) / 2
  1252                                                           adjAdd = -self.glFont.descender
  1253                                                       elif self._alignY == "bottom":
  1254                                                           # Top aligned means scroll between -1 and 0, and adjust for line height
  1255                                                           adjMulti = (-self.scrollbar.markerPos - 1) / 2
  1256                                                           adjAdd = -self.glFont.descender
  1257                                                       else:
  1258                                                           # Center aligned means scroll between -0.5 and 0.5, and 50% adjust for line height
  1259                                                           adjMulti = -self.scrollbar.markerPos / 2
  1260                                                           adjAdd = 0
  1261                                                       self.contentBox._pos.pix = self._pos.pix + (
  1262                                                           0,
  1263                                                           (tightH - areaH) * adjMulti + adjAdd
  1264                                                       )
  1265                                                       self._needVertexUpdate = True
  1266
  1267       100         81.6      0.8      0.0          if self.overflow in ("hidden", "scroll"):
  1268                                                       # Activate aperture
  1269                                                       self.container.enable()
  1270
  1271       100        590.4      5.9      0.1          gl.glPushMatrix()
  1272       100       1831.5     18.3      0.4          self.win.setScale('pix')
  1273
  1274       100        496.4      5.0      0.1          gl.glActiveTexture(gl.GL_TEXTURE0)
  1275       100        992.7      9.9      0.2          gl.glBindTexture(gl.GL_TEXTURE_2D, self.glFont.textureID)
  1276       100        505.5      5.1      0.1          gl.glEnable(gl.GL_TEXTURE_2D)
  1277       100        587.3      5.9      0.1          gl.glDisable(gl.GL_DEPTH_TEST)
  1278
  1279       100        491.3      4.9      0.1          gl.glEnableClientState(gl.GL_VERTEX_ARRAY)
  1280       100        484.7      4.8      0.1          gl.glEnableClientState(gl.GL_COLOR_ARRAY)
  1281       100        499.0      5.0      0.1          gl.glEnableClientState(gl.GL_TEXTURE_COORD_ARRAY)
  1282       100        466.0      4.7      0.1          gl.glEnableClientState(gl.GL_VERTEX_ARRAY)
  1283
  1284       100       1705.5     17.1      0.4          gl.glVertexPointer(2, gl.GL_DOUBLE, 0, self.verticesPix.ctypes)
  1285       100       1485.0     14.8      0.4          gl.glColorPointer(4, gl.GL_DOUBLE, 0, self._colors.ctypes)
  1286       100       1295.5     13.0      0.3          gl.glTexCoordPointer(2, gl.GL_DOUBLE, 0, self._texcoords.ctypes)
  1287
  1288       100       1115.5     11.2      0.3          self.shader.bind()
  1289       100       2361.3     23.6      0.6          self.shader.setInt('texture', 0)
  1290       100       2335.4     23.4      0.6          self.shader.setFloat('pixel', [1.0 / 512, 1.0 / 512])
  1291       100        171.7      1.7      0.0          nVerts = (len(self._text) + len(self._renderChars)) * 4
  1292
  1293       100       5246.1     52.5      1.3          gl.glDrawArrays(gl.GL_QUADS, 0, nVerts)
  1294       100        767.9      7.7      0.2          self.shader.unbind()
  1295
  1296                                                   # removed the colors and font texture
  1297       100        512.7      5.1      0.1          gl.glDisableClientState(gl.GL_COLOR_ARRAY)
  1298       100        473.6      4.7      0.1          gl.glDisableClientState(gl.GL_TEXTURE_COORD_ARRAY)
  1299       100       1135.9     11.4      0.3          gl.glDisableVertexAttribArray(1)
  1300       100        482.8      4.8      0.1          gl.glDisableClientState(gl.GL_VERTEX_ARRAY)
  1301
  1302       100        488.5      4.9      0.1          gl.glActiveTexture(gl.GL_TEXTURE0)
  1303       100        544.3      5.4      0.1          gl.glBindTexture(gl.GL_TEXTURE_2D, 0)
  1304       100        514.5      5.1      0.1          gl.glDisable(gl.GL_TEXTURE_2D)
  1305
  1306       100        478.4      4.8      0.1          if self.hasFocus:  # draw caret line
  1307                                                       self.caret.draw()
  1308
  1309       100        482.6      4.8      0.1          gl.glPopMatrix()
  1310
  1311                                                   # Draw placeholder if blank
  1312       100        265.0      2.6      0.1          if self.editable and len(self.text) == 0:
  1313                                                       self._placeholder.draw()
  1314
  1315       100         93.6      0.9      0.0          if self.container is not None:
  1316                                                       self.container.disable()

  0.33 seconds - C:\Users\adf44\Documents\python\psychopy\psychopy\visual\textbox2\textbox2.py:317 - palette
  0.42 seconds - C:\Users\adf44\Documents\python\psychopy\psychopy\visual\textbox2\textbox2.py:1214 - draw
```

</details>
