### ISSUE TITLE
[Bug]: KeyError: 'GazePoint'

### ISSUE THREAD

**Issue by Whami007** [psychopy/psychopy#6872]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

I tried to run an experiment that uses a GazePoint eye tracker and I received a "Please send the report under "Details" to the developers with a description of what you were doing with the software when the error occurred". Here is the copied error message:

Traceback (most recent call last):
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 1389, in runFile
    self.app.runner.panel.runLocal(event)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\app\runner\runner.py", line 642, in runLocal
    generateScript(
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\scripts\psyexpCompile.py", line 83, in generateScript
    compileScript(infile=exp, version=None, outfile=outfile)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\scripts\psyexpCompile.py", line 221, in compileScript
    _makeTarget(thisExp, outfile, targetOutput)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\scripts\psyexpCompile.py", line 201, in _makeTarget
    script = thisExp.writeScript(outfile, target=targetOutput)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\experiment\_experiment.py", line 323, in writeScript
    self_copy.settings.writeDevicesCode(script)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\experiment\components\settings\__init__.py", line 1436, in writeDevicesCode
    inits['eyetracker'].val = ioDeviceMap[inits['eyetracker'].val]
KeyError: 'GazePoint'

### Expected Behaviour

The experiment should have started and then went into the calibration  routine for the eye tracker. I have the GazePoint plugin installed, directly after the welcome screen are the calibration and validation routines, in this order, and GazePoint control is running in the background and the eye tracker is on. 

### Steps to Reproduce

1.Installed GazePoint plugin
2.Checked to ensure I was running the latest version using a pip command
3. Turned on GazePoint control and ensured eyetracker was on
4. Added calibration and validation routines to my timeline
5. 5. Clicked run experiment and this is when I got the unhandled internal error message
...

**Comment by peircej** [comment]
Hi @Whami007 we fee;l like this was fixed in a previous release of the plugin. Could you check you have the latest version of that by uninstalling and reinstalling it please? You can now uninstall from the plugins dialog

**Comment by peircej** [comment]
The history of that plugin is here, including the fixes you need (we think):
https://github.com/psychopy/psychopy-eyetracker-gazepoint/commits/main/
And that was released a month ago 👍

**Comment by Whami007** [comment]
Hi @peircej, after reinstalling the plugin and making all the changes noted in the Github post you pointed me too, I am still having issues integrating the eyetracker. From my posts on PsychoPy's forum it seems like there are other users having the same issues, with gazepoint as well as tobii. Here is the link https://discourse.psychopy.org/t/integrating-gazepoint-eyetracker/41439  I also had my university's IT services come by and they chalked it up to something the developer would have to fix. I'm sure you all are very busy over there, but if you have the chance to check this out it would be greatly appreciated. Much thanks.

**Comment by MichaelWoodc** [comment]
> Hi [@peircej](https://github.com/peircej), after reinstalling the plugin and making all the changes noted in the Github post you pointed me too, I am still having issues integrating the eyetracker. From my posts on PsychoPy's forum it seems like there are other users having the same issues, with gazepoint as well as tobii. Here is the link https://discourse.psychopy.org/t/integrating-gazepoint-eyetracker/41439 I also had my university's IT services come by and they chalked it up to something the developer would have to fix. I'm sure you all are very busy over there, but if you have the chance to check this out it would be greatly appreciated. Much thanks.

I have a workaround for you!
https://github.com/psychopy/psychopy/issues/7130

```
import socket

# Define connection settings
HOST = "10.10.10.1"  # Change if needed
PORT = 4242  # Replace with correct port if necessary
OUTPUT_FILE = "eye_tracking_data.txt"

# Initialization commands to enable data streams
INIT_COMMANDS = [
    '<SET ID="ENABLE_SEND_COUNTER" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_TIME" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_TIME_TICK" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_FIX" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_LEFT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_RIGHT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_BEST" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPIL_LEFT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPIL_RIGHT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_BLINK" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPILMM" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_DATA" STATE="1" />\r\n',
]

# Open socket connection
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    print(f"Connected to {HOST}:{PORT}")

    # Send initialization commands
    for cmd in INIT_COMMANDS:
        s.sendall(cmd.encode("utf-8"))
    
    print("Initialization complete. Receiving data...")

    # Open file for writing received data
    with open(OUTPUT_FILE, "w") as file:
        try:
            while True:
                data = s.recv(1024)  # Adjust buffer size as needed
                if not data:
                    break  # Stop if connection closes
                
                decoded_data = data.decode("utf-8", errors="ignore")
                file.write(decoded_data)  # Save to file
        except KeyboardInterrupt:
            print("\nStopped by user.")

print(f"Data saved to {OUTPUT_FILE}")
```

For testing this worked perfectly in jupyter notebook (stopping the kernel there simulates a keyboard quit).  You'd just have to figure out the quitting in your code, if needed.  I can't recall what I wound up doing.

**Comment by mdcutone** [comment]
Hello @MichaelWoodc, would you be able to test fixes using your setup? I don't have a GazePoint eyetracker on site, so it would be very helpful if we can work together to fix this issue

**Comment by MichaelWoodc** [comment]
> Hello [@MichaelWoodc](https://github.com/MichaelWoodc), would you be able to test fixes using your setup? I don't have a GazePoint eyetracker on site, so it would be very helpful if we can work together to fix this issue

I've got my hands on one for a few more days, let me know what you had in mind!  I did have that code (or a very small variation of it) working, but we decided to go a different route.  I'll see if I can dig up the .psyexp file as a working example.  For this to work, you just need to do your calibration and everything within the gazepoint control software.  Then you go to your Psychopy experiment.

**Comment by MichaelWoodc** [comment]
The attached .txt file is the python file you can import and use.  It was made based on the gazepoint API (attached).  That should help implement everything.  Hope it helps!

[Gazepoint_API_v2.0.pdf](https://github.com/user-attachments/files/19241104/Gazepoint_API_v2.0.pdf)

[gaze_logger_simple.txt](https://github.com/user-attachments/files/19241103/gaze_logger_simple.txt)

**Comment by mdcutone** [comment]
GazePoint support has been tested and working with the 0.0.4 version of the plugin
