### ISSUE TITLE
Audio of video playing already at end of loading time of the loading component

### ISSUE THREAD

**Issue by estherhazy** [psychopy/psychopy#7297]
I'm playing videos in my experiment in which people talk to the camera and tell a story (~ 15 s duration). For this, I use the load component the routine before the actual video to load the video. This routine is 1.5 s long (no warning appears that this is not enough time to load the video) and I'm presenting a variable on screen during that routine. The issue is that the audio of the video starts before the actual presentation of the video (i.e., at the end of the loading period, only ms!). The audio then stops and continues with the start of the video (so video and audio seem to be synchronous after all, but maybe I cannot detect it because it only lasts for a few ms). At the end, the video seems to freeze. I already reported this in the Psychopy forum: https://discourse.psychopy.org/t/sound-of-video-starts-ms-before-video/44535

I tried everything, changed the different properties of the load component, the duration of the load component, put it in a different routine (then you see that the audio actually starts at the end of the loading period). My workaround now is to add some black frames without any sound in front of the actual video. This way audio + video start together, are synchronous and the video doesn't freeze in the end. It is working but not what I wish for.

I expect that the load component loads the video into the experiment but does not start playing it right away and only when the movie component appears.  If you need any more information, please let me know! 
I'm using Windows 11 and Psychopy Version 2024.2.4

**Comment by mdcutone** [comment]
This bug was fixed in the newest version of PsychoPy where movie playback was reworked to improve responsiveness and audio-visual synchronization. Try it out and let us know if that fixed things on your end :)

**Comment by estherhazy** [comment]
@mdcutone,
I was so excited when I read your comment, but
unfortunately, the problem still persists: you can still hear the beginning of the video before the video routine, then it stops and starts again at the correct time of the video for audio + picture to be synchronous. At the end it freezes and for some videos, the end of audio is also weird.

**Comment by mdcutone** [comment]
@estherhazy Can you provide more information about how you are using the movie component, please?

Here is some information that will help me out:

* Start/stop times in the routine for the movie
* Is force end of routine when finished being used or not?
* What is the format (e.g. mp4, avi, etc.) of the movie and how was is created?
* How long are the movies and what are the dimensions?
* Anything else that might be helpful here along the same lines as above

Thank you
