### ISSUE TITLE
Movie bug freezes computer

### ISSUE THREAD

**Issue by findjoshg** [psychopy/psychopy#970]
Hello,
I am trying to get a film clip to play. I built it on the gui builder with Psychopy v1.82.01 on a 2012 macbook pro OSX Yosemite 10.10.5. It worked when i built it with a placeholder video file but then when i added the 3 second clip, it would play the clip and then freeze the whole computer forcing me to shut the computer down by pressing and holding the power button.
Ive tried using different formats .avi .mov .m4v and nothing works it crashes every time. I went and spoke to my friend who has done alot of psychopy builds and he thinks this is definitely a bug. Does anyone know what this could be and know how to help? Its not letting me attach files. i have tried both .docx and .txt
Many thanks for your help
Josh Gold

**Comment by findjoshg** [comment]
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
This experiment was created using PsychoPy2 Experiment Builder (v1.82.01), Fri Oct  9 13:54:54 2015
If you publish work using this script please cite the relevant PsychoPy publications
  Peirce, JW (2007) PsychoPy - Psychophysics software in Python. Journal of Neuroscience Methods, 162(1-2), 8-13.
  Peirce, JW (2009) Generating stimuli for neuroscience using PsychoPy. Frontiers in Neuroinformatics, 2:10. doi: 10.3389/neuro.11.010.2008
"""

from __future__ import division  # so that 1/3=0.333 instead of 1/3=0
from psychopy import visual, core, data, event, logging, sound, gui
from psychopy.constants import *  # things like STARTED, FINISHED
import numpy as np  # whole numpy lib is available, prepend 'np.'
from numpy import sin, cos, tan, log, log10, pi, average, sqrt, std, deg2rad, rad2deg, linspace, asarray
from numpy.random import random, randint, normal, shuffle
import os  # handy system and path functions

# Ensure that relative paths start from the same directory as this script
_thisDir = os.path.dirname(os.path.abspath(__file__))
os.chdir(_thisDir)

# Store info about the experiment session
expName = 'sports_sim_bug'  # from the Builder filename that created this script
expInfo = {'participant':'', 'session':'001'}
dlg = gui.DlgFromDict(dictionary=expInfo, title=expName)
if dlg.OK == False: core.quit()  # user pressed cancel
expInfo['date'] = data.getDateStr()  # add a simple timestamp
expInfo['expName'] = expName

# Data file name stem = absolute path + name; later add .psyexp, .csv, .log, etc
filename = _thisDir + os.sep + 'data/%s_%s_%s' %(expInfo['participant'], expName, expInfo['date'])

# An ExperimentHandler isn't essential but helps with data saving
thisExp = data.ExperimentHandler(name=expName, version='',
    extraInfo=expInfo, runtimeInfo=None,
    originPath=None,
    savePickle=True, saveWideText=True,
    dataFileName=filename)
#save a log file for detail verbose info
logFile = logging.LogFile(filename+'.log', level=logging.EXP)
logging.console.setLevel(logging.WARNING)  # this outputs to the screen, not a file

endExpNow = False  # flag for 'escape' or other condition => quit the exp

# Start Code - component code to be run before the window creation

# Setup the Window
win = visual.Window(size=(1680, 1050), fullscr=True, screen=0, allowGUI=False, allowStencil=False,
    monitor='testMonitor', color=[0,0,0], colorSpace='rgb',
    blendMode='avg', useFBO=True,
    )
# store frame rate of monitor if we can measure it successfully
expInfo['frameRate']=win.getActualFrameRate()
if expInfo['frameRate']!=None:
    frameDur = 1.0/round(expInfo['frameRate'])
else:
    frameDur = 1.0/60.0 # couldn't get a reliable measure so guess

# Initialize components for Routine "setup"
setupClock = core.Clock()
poz = [.8,-.8]
col_w = [1,1,1]

col_b = [-1,-1,-1]

# Initialize components for Routine "trial"
trialClock = core.Clock()
ISI = core.StaticPeriod(win=win, screenHz=expInfo['frameRate'], name='ISI')
pretest = visual.MovieStim(win=win, name='pretest',
    filename=u'stim1.mp4',
    ori=0, pos=[0, 0], opacity=1,
    depth=-1.0,
    )
polygon = visual.Rect(win=win, name='polygon',
    width=[0.5, 0.5][0], height=[0.5, 0.5][1],
    ori=0, pos=poz,
    lineWidth=1, lineColor=[1,1,1], lineColorSpace='rgb',
    fillColor=col_b, fillColorSpace='rgb',
    opacity=1,depth=-2.0, 
interpolate=True)
polygon_2 = visual.Rect(win=win, name='polygon_2',
    width=[0.3, 0.3][0], height=[0.3, 0.3][1],
    ori=0, pos=poz,
    lineWidth=1, lineColor=[1,1,1], lineColorSpace='rgb',
    fillColor=col_w, fillColorSpace='rgb',
    opacity=1,depth=-3.0, 
interpolate=True)

# Create some handy timers
globalClock = core.Clock()  # to track the time since experiment started
routineTimer = core.CountdownTimer()  # to track time remaining of each (non-slip) routine 

#------Prepare to start Routine "setup"-------
t = 0
setupClock.reset()  # clock 
frameN = -1
# update component parameters for each repeat

# keep track of which components have finished
setupComponents = []
for thisComponent in setupComponents:
    if hasattr(thisComponent, 'status'):
        thisComponent.status = NOT_STARTED

#-------Start Routine "setup"-------
continueRoutine = True
while continueRoutine:
    # get current time
    t = setupClock.getTime()
    frameN = frameN + 1  # number of completed frames (so 0 is the first frame)
    # update/draw components on each frame
    
    
    # check if all components have finished
    if not continueRoutine:  # a component has requested a forced-end of Routine
        break
    continueRoutine = False  # will revert to True if at least one component still running
    for thisComponent in setupComponents:
        if hasattr(thisComponent, "status") and thisComponent.status != FINISHED:
            continueRoutine = True
            break  # at least one component has not yet finished
    
    # check for quit (the Esc key)
    if endExpNow or event.getKeys(keyList=["escape"]):
        core.quit()
    
    # refresh the screen
    if continueRoutine:  # don't flip if this routine is over or we'll get a blank screen
        win.flip()

#-------Ending Routine "setup"-------
for thisComponent in setupComponents:
    if hasattr(thisComponent, "setAutoDraw"):
        thisComponent.setAutoDraw(False)

# the Routine "setup" was not non-slip safe, so reset the non-slip timer
routineTimer.reset()

#------Prepare to start Routine "trial"-------
t = 0
trialClock.reset()  # clock 
frameN = -1
# update component parameters for each repeat
# keep track of which components have finished
trialComponents = []
trialComponents.append(ISI)
trialComponents.append(pretest)
trialComponents.append(polygon)
trialComponents.append(polygon_2)
for thisComponent in trialComponents:
    if hasattr(thisComponent, 'status'):
        thisComponent.status = NOT_STARTED

#-------Start Routine "trial"-------
continueRoutine = True
while continueRoutine:
    # get current time
    t = trialClock.getTime()
    frameN = frameN + 1  # number of completed frames (so 0 is the first frame)
    # update/draw components on each frame
    
    # *pretest* updates
    if t >= 0.0 and pretest.status == NOT_STARTED:
        # keep track of start time/frame for later
        pretest.tStart = t  # underestimates by a little under one frame
        pretest.frameNStart = frameN  # exact frame index
        pretest.setAutoDraw(True)
    
    # *polygon* updates
    if t >= 0.0 and polygon.status == NOT_STARTED:
        # keep track of start time/frame for later
        polygon.tStart = t  # underestimates by a little under one frame
        polygon.frameNStart = frameN  # exact frame index
        polygon.setAutoDraw(True)
    
    # *polygon_2* updates
    if t >= 5 and polygon_2.status == NOT_STARTED:
        # keep track of start time/frame for later
        polygon_2.tStart = t  # underestimates by a little under one frame
        polygon_2.frameNStart = frameN  # exact frame index
        polygon_2.setAutoDraw(True)
    if polygon_2.status == STARTED and t >= (5 + (.1-win.monitorFramePeriod*0.75)): #most of one frame period left
        polygon_2.setAutoDraw(False)
    # *ISI* period
    if t >= 0.0 and ISI.status == NOT_STARTED:
        # keep track of start time/frame for later
        ISI.tStart = t  # underestimates by a little under one frame
        ISI.frameNStart = frameN  # exact frame index
        ISI.start(0.5)
    elif ISI.status == STARTED: #one frame should pass before updating params and completing
        ISI.complete() #finish the static period
    
    # check if all components have finished
    if not continueRoutine:  # a component has requested a forced-end of Routine
        break
    continueRoutine = False  # will revert to True if at least one component still running
    for thisComponent in trialComponents:
        if hasattr(thisComponent, "status") and thisComponent.status != FINISHED:
            continueRoutine = True
            break  # at least one component has not yet finished
    
    # check for quit (the Esc key)
    if endExpNow or event.getKeys(keyList=["escape"]):
        core.quit()
    
    # refresh the screen
    if continueRoutine:  # don't flip if this routine is over or we'll get a blank screen
        win.flip()

#-------Ending Routine "trial"-------
for thisComponent in trialComponents:
    if hasattr(thisComponent, "setAutoDraw"):
        thisComponent.setAutoDraw(False)
# the Routine "trial" was not non-slip safe, so reset the non-slip timer
routineTimer.reset()

win.close()
core.quit()

**Comment by jeremygray** [comment]
please try your movie with the upcoming release, 1.83.00, which has a new movie component (movie3). https://github.com/psychopy/psychopy/releases

**Comment by jeremygray** [comment]
Also: its best to run your experiment in non-fullscreen mode when testing (see experiment settings -> screen). that way, if it should freeze, you can easily switch away from the frozen screen. If you are lucky, you will be able to see an error message within PsychoPy -- that can be a big help to figure out what is happening. And almost always you can force-quit the program, no need to restart the computer.

**Comment by findjoshg** [comment]
great! thank you @jeremygray I will try that and let you know how it goes.
Cheers
Josh

**Comment by findjoshg** [comment]
Hi @jeremygray 
I have loaded up the new version added avbin 10 as it asked, which then allowed it to play the vid.
However i am still having the same freezing problem. it is weird because it worked with another vid, but not this one. NOTE: It's turning the screen white where the video was playing and freezing there.

I have tried the suggestion of running not in full screen and unticked the box in settings but it is still running in full screen.
So now i force quite the player.
It does give me a read out at the end but no error.
"Running: /Users/joshuagold/Desktop/Sports_Sim_Psychopy/sports_sim_bug_lastrun.py 
2015-10-13 14:01:25.663 python[2276:167221] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/59/8f0c74ld69b2znqvz8_5vpqc0000gn/T/org.psychopy.PsychoPy2.savedState"


Below is a list of what i have tried to do.
I tried to load up the same format mp4 but a shorter clip - didnt work.
I changed the polygon timing as i noticed they went longer than the film - still freezes.
i changed the stop time to 5 secs - still freezes
I have tried adding a loop to see if it will push through but nothing. it still freezes
Im very confused.

Please help

Thank you
Josh

**Comment by peircej** [comment]
I think this is an issue with avbin not indicating the end-of-stream for 
the movie. I'm not incluined to try and fix things with avbin though - 
there are too many things that are painful about it.

Could you try the new release though with MovieStim3 instead?

cheers
Jon

On 13/10/15 04:09, Joshua Gold wrote:
>
> Hi @jeremygray <https://github.com/jeremygray>
> I have loaded up the new version added avbin 10 as it asked, which 
> then allowed it to play the vid.
> However i am still having the same freezing problem. it is weird 
> because it worked with another vid, but not this one. NOTE: It's 
> turning the screen white where the video was playing and freezing there.
>
> I have tried the suggestion of running not in full screen and unticked 
> the box in settings but it is still running in full screen.
> So now i force quite the player.
> It does give me a read out at the end but no error.
> "Running: 
> /Users/joshuagold/Desktop/Sports_Sim_Psychopy/sports_sim_bug_lastrun.py
> 2015-10-13 14:01:25.663 python[2276:167221] 
> ApplePersistenceIgnoreState: Existing state will not be touched. New 
> state will be written to 
> /var/folders/59/8f0c74ld69b2znqvz8_5vpqc0000gn/T/org.psychopy.PsychoPy2.savedState"
>
> Below is a list of what i have tried to do.
> I tried to load up the same format mp4 but a shorter clip - didnt work.
> I changed the polygon timing as i noticed they went longer than the 
> film - still freezes.
> i changed the stop time to 5 secs - still freezes
> I have tried adding a loop to see if it will push through but nothing. 
> it still freezes
> Im very confused.
>
> Please help
>
> Thank you
> Josh
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/970#issuecomment-147582806>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by findjoshg** [comment]
Hi @peircej and @jeremygray 
I believe I tried as you suggested and i went into psychopy film component and changed the backend selection (I only saw 3 options: moviepy, avbin and opencv) I tried moviepy and that errored out (See Below). I then tried opencv which managed to play the whole protocol however it skipped through the video and produced a warning message (See Below).

I would like to mention that as a side note when I run a .m4v format with avbin it is the only one out of .mp4, .mpv and .avi that after it freezes it lets me quit out of with esc. All the other formats freeze and it gives me the following error (See Below)

I really appreciate your help here.
It will be nice to get this working

Cheers
Josh

MOVIEPY ERROR
 Running: /Users/joshuagold/Desktop/Sports_Sim_Psychopy/test1/sports_sim_bug_lastrun.py 
2015-10-15 12:28:43.965 python[6277:81199] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/59/8f0c74ld69b2znqvz8_5vpqc0000gn/T/org.psychopy.PsychoPy2.savedState
Traceback (most recent call last):
  File "/Users/joshuagold/Desktop/Sports_Sim_Psychopy/test1/sports_sim_bug_lastrun.py", line 110, in <module>
    depth=-1.0,
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/contrib/lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/visual/movie3.py", line 121, in __init__
    self.loadMovie(self.filename)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/visual/movie3.py", line 168, in loadMovie
    self._audioStream = sound.Sound(self._mov.audio.to_soundarray(),
AttributeError: 'NoneType' object has no attribute 'to_soundarray'

OPENCV ERROR
Running: /Users/joshuagold/Desktop/Sports_Sim_Psychopy/test1/sports_sim_bug_lastrun.py 
5.6704 	WARNING 	t of last frame was 50.14ms (=1/19)
19.7378 	WARNING 	MovieStim2 dropping video frame index: 2
19.7389 	WARNING 	MovieStim2 dropping video frame index: 2
19.7632 	WARNING 	MovieStim2 dropping video frame index: 4
19.7652 	WARNING 	MovieStim2 dropping video frame index: 4
19.7666 	WARNING 	MovieStim2 dropping video frame index: 5
19.7680 	WARNING 	MovieStim2 dropping video frame index: 6
19.7886 	WARNING 	MovieStim2 dropping video frame index: 8
19.7905 	WARNING 	MovieStim2 dropping video frame index: 8
19.7920 	WARNING 	MovieStim2 dropping video frame index: 9
19.7934 	WARNING 	Multiple Movie frames have occurred - I'll stop bothering you about them!
2015-10-15 12:29:22.272 python[6319:81686] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/59/8f0c74ld69b2znqvz8_5vpqc0000gn/T/org.psychopy.PsychoPy2.savedState

AVBIN ,M4V ERROR
Running: /Users/joshuagold/Desktop/Sports_Sim_Psychopy/test1/sports_sim_bug_lastrun.py 
5.3985 	WARNING 	t of last frame was 49.20ms (=1/20)
2015-10-15 12:43:51.395 python[6672:88713] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/59/8f0c74ld69b2znqvz8_5vpqc0000gn/T/org.psychopy.PsychoPy2.savedState

**Comment by findjoshg** [comment]
I have managed to get the videos to play - what i needed to do was make the stop time of the trial shorter than the time of the video itself. The problem with this is that i am looping about 100 short video clips with varying times and so i need to be able to modify the time otherwise i need to be able to allow it to play with an open expected duration without it crashing.

What I have tried:
I have tried many different times but if it goes 1 second over any of the videos then it crashes at that video. 
I have tried no duration also but that crashes it. 
I have also tried the different movie components. moviepy and opencv but they freak out due to sound error (which you can see in above comment)
I have tried to create another condition called duration in my loop file and added $duration to the Stop: expected duration/ time input but it doesn’t impact the timing at all.

Any help is greatly appreciated
Thank you 
Josh

**Comment by czarrar** [comment]
@findjoshg.

I just found this thread because I had the same moviepy issue you mentioned earlier: "AttributeError: 'NoneType' object has no attribute 'to_soundarray'".

I'm not sure if this was your issue but my videos had no audio stream. So if I called MovieStim3 with the noAudio=True argument, it then works fine for me.

**Comment by jeremygray** [comment]
@czarrar: (First things first: Hi! Nice to see you here.)

The moviepy / MovieStim3 AttributeError was recently fixed in 892a74890

**Comment by czarrar** [comment]
@jeremygray: Hi!!! Ok thanks seems like I should get the development version then.

**Comment by fnielsen** [comment]
On Ubuntu 14.04 PsychoPy 1.83.02 with https://github.com/psychopy/psychopy/commit/892a748901934fbb0387ad99419aecde45c89462 (cloned today) I still get `AttributeError: 'NoneType'`. I still need `noAudio=True` to succeed.
